library(tidyverse)
library(magrittr)
library(numform)
library(scales)

AFI98 <- read_csv("raw-lists/AFI-1998.csv")
AFI07 <- read_csv("raw-lists/AFI-2007.csv")
Ebert <- read_csv("raw-lists/Ebert-Great-Movies.csv")
Intl <- read_csv("raw-lists/International-Submissions.csv")
LAFCA <- read_csv("raw-lists/LAFCA-Awards.csv")
NBR <- read_csv("raw-lists/NBR-Awards.csv")
NSFC <- read_csv("raw-lists/NSFC-Awards.csv")
NYFCC <- read_csv("raw-lists/NYFCC-Awards.csv")
Oscars <- read_csv("raw-lists/OscarCeremonies.csv")
